### ISSUE TITLE
Error saving as PNG

### ISSUE THREAD

**Issue by rufuscreeley** [densitydesign/raw#102] opened 2016-11-05 16:15 UTC
When I try to save as png nothing happens. The button doesn't work.
Thanks!

**Comment by Linneawikstrom** [comment] 2016-12-14 12:22
I have the same issue. Will this be fixed soon? Or shall i try something else?

Thanks,
Linnea

**Comment by mikima** [comment] 2017-01-04 12:04
Duplicate of #104 #105

**Closed by mikima** 2017-01-04 12:04 UTC

**Comment by robroc** [comment] 2018-05-28 19:10
Has this been fixed for all chart types? I'm getting the same problem with bump charts and streamgraphs specifically. On Chrome/Windows.
